version: '3.9'
services:
  mysql-user-service:
    image:  mysql:latest
    container_name: mysql-user-service
    networks:
      - user-network
    ports:
      - 3306:3306

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD:  "yes"

  user-authentication-service:
    image: user-auth
    container_name: user-authentication-service
    build:  ./
    networks:
      - user-network
    ports:
      - 9001:9001
    depends_on:
          - mysql-user-service

networks:
  user-network:
    driver: bridge







